name: Develop GPR

on:
  push:
    branches: [ "develop" ]

env:
  REPOSITORY_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
        source-url: ${{ env.REPOSITORY_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build and Restore dependencies
      run: dotnet build -c Release Udap.Metadata.Vonk.Server.sln

